"""First migration

Revision ID: d76e566a8fa3
Revises: 884d798d0827
Create Date: 2023-07-14 15:48:01.800598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd76e566a8fa3'
down_revision = '884d798d0827'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
